# Generated by Django 3.2.3 on 2021-05-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=140)),
                ('Email', models.EmailField(max_length=140)),
                ('Password', models.CharField(max_length=140)),
                ('Cpassword', models.CharField(max_length=140)),
            ],
            options={
                'ordering': ['User_name'],
            },
        ),
    ]
